* Description
Consider a "word" as any sequence of capital letters A-Z (not limited to just "dictionary words"). For any word with at least two different letters, there are other words composed of the same letters but in a different order (for instance, STATIONARILY/ANTIROYALIST, which happen to both be dictionary words; for our purposes "AAIILNORSTTY" is also a "word" composed of the same letters as these two).

We can then assign a number to every word, based on where it falls in an alphabetically sorted list of all words made up of the same group of letters. One way to do this would be to generate the entire list of words and find the desired one, but this would be slow if the word is long.

Given a word, return its number. Your function should be able to accept any word 25 letters or less in length (possibly with some letters repeated), and take no more than 500 milliseconds to run. To compare, when the solution code runs the 27 test cases in JS, it takes 101ms.

For very large words, you'll run into number precision issues in JS (if the word's position is greater than 2^53). For the JS tests with large positions, there's some leeway (.000000001%). If you feel like you're getting it right for the smaller ranks, and only failing by rounding on the larger, submit a couple more times and see if it takes.

Python, Java and Haskell have arbitrary integer precision, so you must be precise in those languages (unless someone corrects me).

C# is using a long, which may not have the best precision, but the tests are locked so we can't change it.

Sample words, with their rank:
ABAB = 2
AAAB = 1
BAAA = 4
QUESTION = 24572
BOOKKEEPER = 10743
* Solutions

#+BEGIN_SRC python :results output
  import unittest
  from collections import Counter
  from functools import reduce


  def listPosition(word):
      if len(word) == 1:
          return 1
      sorted_list = sorted(set(word))
      index = sorted_list.index(word[0])
      res = 0
      for i in sorted_list[:index]:
          temp = list(word)
          temp.remove(i)
          res += cal_num(temp)
      return res + listPosition(word[1:])


  def cal_num(rest_word):
      char_dict = Counter(rest_word)
      mul = 1
      n = len(rest_word)
      for i in char_dict.values():
          mul *= nCr(n, i)
          n -= i
      return mul


  def nCr(n, r):
      r = min(r, n - r)
      numer = reduce(lambda x, y: x * y, range(n, n - r, -1), 1)
      denom = reduce(lambda x, y: x * y, range(1, r + 1), 1)
      return numer // denom


  class TestCase(unittest.TestCase):
      def test_cases(self):
          testValues = {
              'A': 1,
              'ABAB': 2,
              'AAAB': 1,
              'BAAA': 4,
              'QUESTION': 24572,
              'BOOKKEEPER': 10743
          }
          for word in testValues:
              self.assertEqual(listPosition(word), testValues[word])


  unittest.main()
#+END_SRC

#+RESULTS:
