* Description
On an 8 x 8 chessboard, there is one white rook.  There also may be empty squares, white bishops, and black pawns.  These are given as characters 'R', '.', 'B', and 'p' respectively. Uppercase characters represent white pieces, and lowercase characters represent black pieces.

The rook moves as in the rules of Chess: it chooses one of four cardinal directions (north, east, west, and south), then moves in that direction until it chooses to stop, reaches the edge of the board, or captures an opposite colored pawn by moving to the same square it occupies.  Also, rooks cannot move into the same square as other friendly bishops.

Return the number of pawns the rook can capture in one move.


Example 1:

Input: [[".",".",".",".",".",".",".","."],[".",".",".","p",".",".",".","."],[".",".",".","R",".",".",".","p"],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".","p",".",".",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]]
Output: 3
Explanation:
In this example the rook is able to capture all the pawns.

Example 2:

Input: [[".",".",".",".",".",".",".","."],[".","p","p","p","p","p",".","."],[".","p","p","B","p","p",".","."],[".","p","B","R","B","p",".","."],[".","p","p","B","p","p",".","."],[".","p","p","p","p","p",".","."],[".",".",".",".",".",".",".","."],[".",".",".",".",".",".",".","."]]
Output: 0
Explanation:
Bishops are blocking the rook to capture any pawn.

Example 3:

Input: [[".",".",".",".",".",".",".","."],[".",".",".","p",".",".",".","."],[".",".",".","p",".",".",".","."],["p","p",".","R",".","p","B","."],[".",".",".",".",".",".",".","."],[".",".",".","B",".",".",".","."],[".",".",".","p",".",".",".","."],[".",".",".",".",".",".",".","."]]
Output: 3
Explanation:
The rook can capture the pawns at positions b5, d6 and f5.

Note:

    board.length == board[i].length == 8
    board[i][j] is either 'R', '.', 'B', or 'p'
    There is exactly one cell with board[i][j] == 'R'
* Solution
#+begin_src python
class Solution:
    def numRookCaptures(self, board: List[List[str]]) -> int:
        t = False
        for i in range(8):
            for j in range(8):
                if board[i][j] == 'R':
                    t = True
                    break
            if t:
                break

        rv = 0
        k = i
        while k > 0:
            t = board[k - 1][j]
            if t == 'B':
                break
            if t == 'p':
                rv += 1
                break
            k -= 1

        k = i
        while k < 7:
            t = board[k+1][j]
            if t == 'B':
                break
            if t == 'p':
                rv += 1
                break
            k += 1
        k = j
        while k > 0:
            t = board[i][k-1]
            if t == 'B':
                break
            if t == 'p':
                rv += 1
                break
            k -= 1
        k = k
        while k < 7:
            t = board[i][k+1]
            if t == 'B':
                break
            if t == 'p':
                rv += 1
                break
            k += 1
        return rv
#+end_src
