* Description
You are a product manager and currently leading a team to develop a new product. Unfortunately, the latest version of your product fails the quality check. Since each version is developed based on the previous version, all the versions after a bad version are also bad.

Suppose you have n versions [1, 2, ..., n] and you want to find out the first bad one, which causes all the following ones to be bad.

You are given an API bool isBadVersion(version) which will return whether version is bad. Implement a function to find the first bad version. You should minimize the number of calls to the API.

Example:

Given n = 5, and version = 4 is the first bad version.

call isBadVersion(3) -> false
call isBadVersion(5) -> true
call isBadVersion(4) -> true

Then 4 is the first bad version.
* Solution
#+BEGIN_SRC cpp
  #include <iostream>
  using namespace std;

  bool isBadVersion(int version);

  class Solution {
  public:
    int helper(int former, int latter) {
      if (former == latter)
        return former;
      if (latter - former == 1) {
        if (isBadVersion(former)) {
          return former;
        } else {
          return latter;
        }
      }
      long middle = former;
      middle += latter;
      middle = middle / 2;
      if (isBadVersion(middle))
        return helper(former, middle);
      return helper(middle, latter);
    }
    int firstBadVersion(int n) { return helper(1, n); }
  };
#+END_SRC
