* Description
Given an undirected tree consisting of n vertices numbered from 1 to n. A frog starts jumping from the vertex 1. In one second, the frog jumps from its current vertex to another unvisited vertex if they are directly connected. The frog can not jump back to a visited vertex. In case the frog can jump to several vertices it jumps randomly to one of them with the same probability, otherwise, when the frog can not jump to any unvisited vertex it jumps forever on the same vertex.

The edges of the undirected tree are given in the array edges, where edges[i] = [fromi, toi] means that exists an edge connecting directly the vertices fromi and toi.

Return the probability that after t seconds the frog is on the vertex target.

Example 1:

Input: n = 7, edges = [[1,2],[1,3],[1,7],[2,4],[2,6],[3,5]], t = 2, target = 4
Output: 0.16666666666666666
Explanation: The figure above shows the given graph. The frog starts at vertex 1, jumping with 1/3 probability to the vertex 2 after second 1 and then jumping with 1/2 probability to vertex 4 after second 2. Thus the probability for the frog is on the vertex 4 after 2 seconds is 1/3 * 1/2 = 1/6 = 0.16666666666666666.

Example 2:

Input: n = 7, edges = [[1,2],[1,3],[1,7],[2,4],[2,6],[3,5]], t = 1, target = 7
Output: 0.3333333333333333
Explanation: The figure above shows the given graph. The frog starts at vertex 1, jumping with 1/3 = 0.3333333333333333 probability to the vertex 7 after second 1.

Example 3:

Input: n = 7, edges = [[1,2],[1,3],[1,7],[2,4],[2,6],[3,5]], t = 20, target = 6
Output: 0.16666666666666666

Constraints:

    1 <= n <= 100
    edges.length == n-1
    edges[i].length == 2
    1 <= edges[i][0], edges[i][1] <= n
    1 <= t <= 50
    1 <= target <= n
    Answers within 10^-5 of the actual value will be accepted as correct.
* Solution
#+begin_src python :session solution
from typing import List
from collections import defaultdict

class Solution:
    def frogPosition(self, n: int, edges: List[List[int]], t: int, target: int) -> float:
        if n == 1:
            return 1.0
        tree = defaultdict(list)
        for f,k in edges:
            tree[f].append(k)
            tree[k].append(f)
        def dfs(t, cur, prev):
            next_level = [i for i in tree[cur] if i != prev]
            if t == 0 or len(next_level) == 0:
                if cur == target:
                    return 1.0
                return 0
            p = 1 / len(next_level)
            rv = 0
            for i in next_level:
                rv += dfs(t-1, i, cur) * p
            return rv
        rv = 0
        nexts = tree[1]
        p = 1/len(nexts)
        for i in nexts:
            rv += dfs(t-1, i, 1) *p
        return rv


#+end_src

#+begin_src python
n = 7
edges = [[1,2],[1,3],[1,7],[2,4],[2,6],[3,5]]
t = 2
target = 4

solution = Solution()
print(solution.frogPosition(n, edges, t, target))
#+end_src


#+begin_src cpp
class Solution {
    class  node{
        int id;
        double p;
        int t;
        node(int i,double pp,int tt){
            id=i;
            p=pp;
            t=tt;
        }
    }
    public double frogPosition(int n, int[][] edges, int t, int target) {
        Set<Integer>[] sets=new Set[n+1];
        for(int i=0;i<=n;i++) sets[i]=new HashSet<Integer>();
        for(int[] e:edges){
            sets[e[0]].add(e[1]);
            sets[e[1]].add(e[0]);
        }
        Queue<node> q=new LinkedList<>();
        q.add(new node(1,1.000000,0));
        boolean[] vis=new boolean[n+1];
        vis[1]=true;
        while(!q.isEmpty()){
            node u=q.poll();
            if(u.t==t&&u.id==target){
                return u.p;
            }
            int sz=0;
            for(int nb:sets[u.id]) if(!vis[nb]) sz++;
            if(u.t<t){
                boolean find=false;
                for(int nb:sets[u.id]){
                    if(vis[nb]) continue;
                    find=true;
                    vis[nb]=true;
                    q.add(new node(nb,u.p/sz,u.t+1));
                }
                if(find==false){
                    q.add(new node(u.id,u.p,u.t+1));
                }
            }

        }
        return 0.0;

    }
}
#+end_src
