* Description
According to the Wikipedia's article: "The Game of Life, also known simply as Life, is a cellular automaton devised by the British mathematician John Horton Conway in 1970."

Given a board with m by n cells, each cell has an initial state live (1) or dead (0). Each cell interacts with its eight neighbors (horizontal, vertical, diagonal) using the following four rules (taken from the above Wikipedia article):

    Any live cell with fewer than two live neighbors dies, as if caused by under-population.
    Any live cell with two or three live neighbors lives on to the next generation.
    Any live cell with more than three live neighbors dies, as if by over-population..
    Any dead cell with exactly three live neighbors becomes a live cell, as if by reproduction.

Write a function to compute the next state (after one update) of the board given its current state. The next state is created by applying the above rules simultaneously to every cell in the current state, where births and deaths occur simultaneously.

Example:

Input:
[
  [0,1,0],
  [0,0,1],
  [1,1,1],
  [0,0,0]
]
Output:
[
  [0,0,0],
  [1,0,1],
  [0,1,1],
  [0,1,0]
]

Follow up:

    Could you solve it in-place? Remember that the board needs to be updated at the same time: You cannot update some cells first and then use their updated values to update other cells.
    In this question, we represent the board using a 2D array. In principle, the board is infinite, which would cause problems when the active area encroaches the border of the array. How would you address these problems?
* Solution
#+begin_src python
class Solution:
    def gameOfLife(self, board: List[List[int]]) -> None:
        """
        Do not return anything, modify board in-place instead.
        """
        n = len(board)
        if n == 0:
            return
        m = len(board[0])
        if m == 0:
            return
        offset = ((0,1), (0,-1), (1,0),(-1,0), (1,1), (-1,-1), (1,-1), (-1,1))
        current_mask = 1
        for i in range(n):
            for j in range(m):
                live_num = 0
                for x,y in offset:
                    if 0<= i+x < n and 0<= j+y < m:
                        live_num += board[i+x][j+y] & current_mask
                if board[i][j] == 1:
                    if live_num in (2,3):
                        board[i][j] += 2
                if board[i][j] == 0:
                    if live_num == 3:
                        board[i][j] += 2
        for i in range(n):
            for j in range(m):
                board[i][j] = (board[i][j] & 2) >> 1
#+end_src
