* Description
Your friend is typing his name into a keyboard.  Sometimes, when typing a character c, the key might get long pressed, and the character will be typed 1 or more times.

You examine the typed characters of the keyboard.  Return True if it is possible that it was your friends name, with some characters (possibly none) being long pressed.



Example 1:

Input: name = "alex", typed = "aaleex"
Output: true
Explanation: 'a' and 'e' in 'alex' were long pressed.

Example 2:

Input: name = "saeed", typed = "ssaaedd"
Output: false
Explanation: 'e' must have been pressed twice, but it wasn't in the typed output.

Example 3:

Input: name = "leelee", typed = "lleeelee"
Output: true

Example 4:

Input: name = "laiden", typed = "laiden"
Output: true
Explanation: It's not necessary to long press any character.

Note:

    name.length <= 1000
    typed.length <= 1000
    The characters of name and typed are lowercase letters.
* Solution
#+begin_src python
class Solution:
    def isLongPressedName(self, name: str, typed: str) -> bool:
        length_name = len(name)
        length_typed = len(typed)
        if length_name == 0:
            if length_typed > 0:
                return False
            return True
        if length_typed == 0 or name[0] != typed[0]:
            return False
        j = 1
        for i in range(1, length_typed):
            if j < length_name and typed[i] == name[j]:
                j += 1
            elif typed[i] != name[j-1]:
                return False

        if j != length_name:
            return False
        return True
#+end_src
