* Description
In a row of seats, 1 represents a person sitting in that seat, and 0 represents that the seat is empty.

There is at least one empty seat, and at least one person sitting.

Alex wants to sit in the seat such that the distance between him and the closest person to him is maximized.

Return that maximum distance to closest person.

Example 1:

Input: [1,0,0,0,1,0,1]
Output: 2
Explanation:
If Alex sits in the second open seat (seats[2]), then the closest person has distance 2.
If Alex sits in any other open seat, the closest person has distance 1.
Thus, the maximum distance to the closest person is 2.

Example 2:

Input: [1,0,0,0]
Output: 3
Explanation:
If Alex sits in the last seat, the closest person is 3 seats away.
This is the maximum distance possible, so the answer is 3.

Note:

    1 <= seats.length <= 20000
    seats contains only 0s or 1s, at least one 0, and at least one 1.
* Solution
#+begin_src python
class Solution:
    def maxDistToClosest(self, seats: List[int]) -> int:
        i = 0
        j = 0
        rv = 0
        while i < len(seats):
            for j in range(i+1, len(seats)):
                if seats[j] == 1:
                    if seats[i] == 0:
                        rv = max(rv, j - i )
                    else:
                        rv = max(rv, (j-i) // 2)
                    i = j
                    break
            else:
                return max(rv, len(seats) - i - 1)
        return rv
#+end_src
