* Description
A quadtree is a tree data in which each internal node has exactly four children: topLeft, topRight, bottomLeft and bottomRight. Quad trees are often used to partition a two-dimensional space by recursively subdividing it into four quadrants or regions.

We want to store True/False information in our quad tree. The quad tree is used to represent a N * N boolean grid. For each node, it will be subdivided into four children nodes until the values in the region it represents are all the same. Each node has another two boolean attributes : isLeaf and val. isLeaf is true if and only if the node is a leaf node. The val attribute for a leaf node contains the value of the region it represents.

For example, below are two quad trees A and B:

A:
+-------+-------+   T: true
|       |       |   F: false
|   T   |   T   |
|       |       |
+-------+-------+
|       |       |
|   F   |   F   |
|       |       |
+-------+-------+
topLeft: T
topRight: T
bottomLeft: F
bottomRight: F

B:
+-------+---+---+
|       | F | F |
|   T   +---+---+
|       | T | T |
+-------+---+---+
|       |       |
|   T   |   F   |
|       |       |
+-------+-------+
topLeft: T
topRight:
     topLeft: F
     topRight: F
     bottomLeft: T
     bottomRight: T
bottomLeft: T
bottomRight: F



Your task is to implement a function that will take two quadtrees and return a quadtree that represents the logical OR (or union) of the two trees.

A:                 B:                 C (A or B):
+-------+-------+  +-------+---+---+  +-------+-------+
|       |       |  |       | F | F |  |       |       |
|   T   |   T   |  |   T   +---+---+  |   T   |   T   |
|       |       |  |       | T | T |  |       |       |
+-------+-------+  +-------+---+---+  +-------+-------+
|       |       |  |       |       |  |       |       |
|   F   |   F   |  |   T   |   F   |  |   T   |   F   |
|       |       |  |       |       |  |       |       |
+-------+-------+  +-------+-------+  +-------+-------+

Note:

    Both A and B represent grids of size N * N.
    N is guaranteed to be a power of 2.
    If you want to know more about the quad tree, you can refer to its wiki.
    The logic OR operation is defined as this: "A or B" is true if A is true, or if B is true, or if both A and B are true.
* Solution
#+begin_src python
class Solution:
    def intersect(self, quadTree1: 'Node', quadTree2: 'Node') -> 'Node':
        rv = quadTree1
        def _helper(a, b):
            if b is None or (a.isLeaf and a.val) or (b.isLeaf and not b.val):
                return
            if (a.isLeaf and not a.val) or (b.isLeaf and b.val):
                a.topLeft = b.topLeft
                a.topRight = b.topRight
                a.bottomLeft = b.bottomLeft
                a.bottomRight = b.bottomRight
                a.val = b.val
                a.isLeaf = b.isLeaf
                return
            _helper(a.bottomLeft,b.bottomLeft)
            _helper(a.bottomRight, b.bottomRight)
            _helper(a.topRight, b.topRight)
            _helper(a.topLeft, b.topLeft)
            if a.bottomLeft.val and a.bottomRight.val and a.topLeft.val and a.topRight.val:
                a.val = True
                a.isLeaf = True
                a.bottomRight = None
                a.bottomLeft = None
                a.topRight = None
                a.topLeft = None
        _helper(quadTree1, quadTree2)
        return rv
#+end_src

