* Description
Given an array of characters, compress it in-place.

The length after compression must always be smaller than or equal to the original array.

Every element of the array should be a character (not int) of length 1.

After you are done modifying the input array in-place, return the new length of the array.

Follow up:
Could you solve it using only O(1) extra space?

Example 1:

Input:
["a","a","b","b","c","c","c"]

Output:
Return 6, and the first 6 characters of the input array should be: ["a","2","b","2","c","3"]

Explanation:
"aa" is replaced by "a2". "bb" is replaced by "b2". "ccc" is replaced by "c3".

Example 2:

Input:
["a"]

Output:
Return 1, and the first 1 characters of the input array should be: ["a"]

Explanation:
Nothing is replaced.

Example 3:

Input:
["a","b","b","b","b","b","b","b","b","b","b","b","b"]

Output:
Return 4, and the first 4 characters of the input array should be: ["a","b","1","2"].

Explanation:
Since the character "a" does not repeat, it is not compressed. "bbbbbbbbbbbb" is replaced by "b12".
Notice each digit has it's own entry in the array.

Note:

    All characters have an ASCII value in [35, 126].
    1 <= len(chars) <= 1000.

* Solution
#+BEGIN_SRC cpp
  #include <iostream>
  #include <math.h>
  #include <vector>
  using namespace std;

  class Solution {
  public:
    int compress(vector<char> &chars) {
      if (chars.size() <= 1)
        return chars.size();
      int length = 2;
      char former_char = chars[0];
      for (int i = 1; i < chars.size(); i++) {
        if (chars[i] == former_char) {
          if (chars[i] == chars[i - 1])
            chars[length] = (char)2;
          else if (chars[i - 1] == '9') {
            int j = i - 1;
            int num = 0;
            for (; j > 1; j--) {
              if (chars[j] > '9' && chars[j] < '0') {
                num = (int)chars[j] * (pow(10, i - 1 - j)) + num;
                break;
              }
            }
            for (; j < i; j++) {

            }
          }
        } else {
          length++;
          former_char = chars[i];
        }
      }
    }
  };
#+END_SRC
